services:
    # Url Pool
    umanit_seo.url_history.url_pool:
        class: Umanit\SeoBundle\UrlHistory\UrlPool
        arguments: ['@doctrine.orm.entity_manager','%kernel.default_locale%']
        calls:
            - [setAnnotationReader, ['@annotations.cached_reader']]
    Umanit\SeoBundle\UrlHistory\UrlPool: '@umanit_seo.url_history.url_pool'

    # Canonical url generator
    umanit_seo.routing.canonical:
        class: Umanit\SeoBundle\Routing\Canonical
        arguments:
            - '@router'
            - '@umanit_seo.routable'

    Umanit\SeoBundle\Routing\Canonical: '@umanit_seo.routing.canonical'

    # Url History Writer
    umanit_seo.event_subscriber.url_history_writer:
        class: Umanit\SeoBundle\Doctrine\EventSubscriber\UrlHistoryWriter
        arguments:
            - '@umanit_seo.url_history.url_pool'
            - '@umanit_seo.routing.canonical'
            - '@cache.app'
            - '%kernel.default_locale%'
            - '%umanit_seo.use_url_historization%'
        calls:
            - [setAnnotationReader, ['@annotations.cached_reader']]
        tags: ['doctrine.event_subscriber']
    Umanit\SeoBundle\Doctrine\EventSubscriber\UrlHistoryWriter: '@umanit_seo.event_subscriber.url_history_writer'

    # Current Entity Resolver
    umanit_seo.doctrine_event_subscriber.current_entity_resolver:
        class: Umanit\SeoBundle\Doctrine\EventSubscriber\CurrentEntityResolver
        arguments: ['@umanit_seo.runtime.current_seo_entity', '@umanit_seo.routing.canonical', '@request_stack']
        tags:
            - { name: doctrine.event_subscriber }

    umanit_seo.event_subscriber.url_redirector:
        class: Umanit\SeoBundle\EventSubscriber\UrlRedirector
        arguments:
            - '@umanit_seo.url_history.url_pool'
            - '%umanit_seo.use_url_historization%'
            - '%umanit_seo.redirect_code%'
        tags:
            - { name: kernel.event_subscriber }
    Umanit\SeoBundle\EventSubscriber\UrlRedirector: '@umanit_seo.event_subscriber.url_redirector'

    umanit_seo.breadcrumb.breadcrumb_builder:
        class: Umanit\SeoBundle\Breadcrumb\BreadcrumbBuilder
        arguments:
            - '@twig'
            - '@umanit_seo.routing.canonical'
            - '@umanit_seo.breadcrumbable'
            - '%umanit_seo.templates%'

    Umanit\SeoBundle\Breadcrumb\BreadcrumbBuilder: '@umanit_seo.breadcrumb.breadcrumb_builder'

    # Twig Extension
    umanit_seo.runtime_twig.seo_extension:
        class: Umanit\SeoBundle\Runtime\Twig\SeoExtension
        arguments:
            - '@umanit_seo.routing.canonical'
            - '@umanit_seo.runtime.current_seo_entity'
            - '@umanit_seo.utils.seo_metadata_resolver'
            - '@umanit_seo.schema_org.schema_org_resolver'
            - '@umanit_seo.breadcrumb.breadcrumb_builder'
        tags:
            - { name: twig.extension }
    Umanit\SeoBundle\Runtime\Twig\SeoExtension: '@umanit_seo.runtime_twig.seo_extension'

    umanit_seo.twig_extension.routing:
        class: Umanit\SeoBundle\Runtime\Twig\RoutingExtension
        arguments:
            - '@twig.extension.routing'
            - '@umanit_seo.routing.canonical'
        tags:
            - { name: twig.extension }

    # CurrentSeo Entity
    umanit_seo.runtime.current_seo_entity:
        class: Umanit\SeoBundle\Runtime\CurrentSeoEntity
    Umanit\SeoBundle\Runtime\CurrentSeoEntity: '@umanit_seo.runtime.current_seo_entity'

    # Utils
    umanit_seo.utils_entity_parser.excerpt:
        class: Umanit\SeoBundle\Utils\EntityParser\Excerpt
        arguments: ['@property_accessor']
    Umanit\SeoBundle\Utils\EntityParser\Excerpt: '@umanit_seo.utils_entity_parser.excerpt'

    umanit_seo.utils_entity_parser.title:
        class: Umanit\SeoBundle\Utils\EntityParser\Title
        arguments: ['@property_accessor']
    Umanit\SeoBundle\Utils\EntityParser\Title: '@umanit_seo.utils_entity_parser.title'

    # Forms
    umanit_seo.form_type.seo_metadata_type:
        class: Umanit\SeoBundle\Form\Type\SeoMetadataType
        arguments: ['@umanit_seo.utils.seo_metadata_resolver', '@translator', '@doctrine.orm.entity_manager','%umanit_seo.metadata%']
        tags:
            - { name: form.type, alias: Umanit\SeoBundle\Form\Type\SeoMetadataType }
    Umanit\SeoBundle\Form\Type\SeoMetadataType: '@umanit_seo.form_type.seo_metadata_type'

    # Metadata Resolver
    umanit_seo.utils.seo_metadata_resolver:
        class: Umanit\SeoBundle\Utils\SeoMetadataResolver
        arguments: ['@umanit_seo.utils_entity_parser.title', '@umanit_seo.utils_entity_parser.excerpt', '%umanit_seo.metadata%']
    Umanit\SeoBundle\Utils\SeoMetadataResolver: '@umanit_seo.utils.seo_metadata_resolver'

    # SchemaOrg Resolver
    umanit_seo.schema_org.schema_org_resolver:
        class: Umanit\SeoBundle\SchemaOrg\SchemaOrgResolver
        calls:
            - [setAnnotationReader, ['@annotations.cached_reader']]
            - [setContainer, ['@service_container']]
    Umanit\SeoBundle\SchemaOrg\SchemaOrgResolver: '@umanit_seo.schema_org.schema_org_resolver'

    # Routable
    umanit_seo.routable:
        class: Umanit\SeoBundle\Handler\Routable\Routable
        arguments: [!tagged_iterator umanit_seo.routable.handler]

    Umanit\SeoBundle\Handler\Routable\RoutableInterface: '@umanit_seo.routable'

    # Breadcrumbable
    umanit_seo.breadcrumbable:
        class: Umanit\SeoBundle\Handler\Breadcrumbable\Breadcrumbable
        arguments: [!tagged_iterator umanit_seo.breadcrumbable.handler]

    Umanit\SeoBundle\Handler\Breadcrumbable\BreadcrumbableInterface: '@umanit_seo.breadcrumbable'
