sonata_admin:
    # Extension for adding "Show on site" to seo bundle admins
    extensions:
        umanit_seo.admin.extension.seo_admin_extension:
            implements:
                - Umanit\SeoBundle\Model\HasSeoMetadataInterface
services:
    umanit_seo.admin.extension.seo_admin_extension:
        class: Umanit\SeoBundle\Sonata\AdminExtension\SeoAdminExtension
        tags:
            - { name: sonata.admin.extension }
